services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
  dbviewer:
    image: sqlpad/sqlpad:5
    depends_on:
      - db
    ports:
      - 3000:3000
    environment:
      SQLPAD_AUTH_DISABLED: "true"
      SQLPAD_AUTH_DISABLED_DEFAULT_ROLE: "admin"
      SQLPAD_CONNECTIONS__pgdemo__name: "Postgres"
      SQLPAD_CONNECTIONS__pgdemo__driver: "postgres"
      SQLPAD_CONNECTIONS__pgdemo__host: "db"
      SQLPAD_CONNECTIONS__pgdemo__database: ${POSTGRES_DB}
      SQLPAD_CONNECTIONS__pgdemo__username: ${POSTGRES_USER}
      SQLPAD_CONNECTIONS__pgdemo__password: ${POSTGRES_PASSWORD}
  app:
    image: ghcr.io/omar-besbes/rust-app:latest
    build:
      context: .
    depends_on:
      - db
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}"
    ports:
      - 8080:8080

volumes:
  postgres_data:
    driver: local
